.TH EPTS "5" "May 2018" "epts VERSION" "File Formats and Conversions"
.SH NAME
epts \- epts file format
.SH DESCRIPTION
The program
.B epts
allows its state to be saved in XML files that use the file extension
.BR epts .
.PP
This file starts with the following lines:
.IP
.B
<?xml version="1.1" encoding="UTF-8"?>
.br
.B
<!DOCTYPE\ images\ PUBLIC\ "-//BZDev//EPTS-1.0//EN"
.br
.B
\ \ \ \ \ \ \ \ \ \ "sresource:epts-1.0.dtd">
.br
.B
<epts xmlns="http://bzdev.org/DTD/epts-1.0">
.PP
This is followed by an "image" element:
.IP
.B
<image width="\fIWIDTH\fB" height="\fIHEIGHT\fB" imageURIExists="\fIVALUE\fB"\>
.PP
where
.I WIDTH
is the image width,
.I HEIGHT
is the image height,
and
.I VALUE
is
.B true
if an image file is specified, and
.B false
if not. When an image file is specified, the
.B width
and
.B height
fields for this element are those of the image. When the
.B imageURIExists
field is
.BR true ,
the image URI will be provided in the following
.B targetList
element described below and the specified dimensions are expected to
match those of the image (this allows a crosscheck to verify that the
image dimensions have not changed due to an update as the image itself is not
part of this file).
.PP
The
.B targetList
element does not have any attributes, using a sequence of
.B argument
elements instead:
.IP
.B
<targetList>
.br
.B
\ \ \ \ <argument>\fICDATA\fB</argument> ...
.br
.B </targetList>
.PP
where
.I CDATA
is an XML character sequence. Predefined entities must be used
to quote characters reserved by XML. Any other entity reference must
not be used. For the case where the preceding
.B image
element specified
.B true
for its
.B imageURIExists
attribute's value, there is a single argument that represents the URI
for the image. When this URI is an relative URI, it must refer to a
subdirectory of the directory in which the EPTS file is located, or
that directory itself.
.PP
The target-list is followed by a
.B gcsconfig
element:
.IP
.B
<gcsconfig unitIndex="\fIIND1\B" refPointIndex="\fIIND2\fB"
.br
\ \ \ \ \ \ \ userSpaceDistance="\fIUDIST\fB"
.br
\ \ \ \ \ \ \ gcsDistance="\fIGCSDIST\fB"
.br
\ \ \ \ \ \ \ xorigin="\fIXORIGIN\fB" yorigin="\fIYORIGIN\fB"/>
.PP
where
.I IND1
has values in the range [0, 10] corresponding to "custom units", "nm",
"um", "mm", "cm", "m", "km","inches", "feet", "yards", and "miles"
respectively.  Similarly,
.I IND2
has values in the range [0, 8] corresponding to "UPPER_LEFT",
"UPPER_CENTER", "UPPER_RIGHT", "CENTER_LEFT", "CENTER",
"CENTER_RIGHT", "LOWER_LEFT", "LOWER_CENTER", and "LOWER_RIGHT"
respectively. The value
.I UDIST
is a distance in image-space (or user space) coordinates and
.I GCSDIST
is the corresponding distance in graph coordinate space, using the units
corresponding to the value of
.IR IND1 .
Unless specified in custom units or meters, the
.I GCSDIST
value will be converted to meters before it is used.
The values for
.I XORIGIN
and
.I YORIGIN
are the X-Y coordinates of the image's reference point
in graph coordinate space units (custom units if
.I IND1
is 0; otherwise meters), so no unit conversion is used for these
quantities.
.PP
The next element is a
.B table
element, which does not specify any attributes, but contains a sequence
of
.B row
elements:
.IP
.B
<table>
.br
.B
\ \ \ <row varname="\fINAME\fB" type="\fITYPE\fB"
.br
.B
\ \ \ \ \ \ \ \ x="X" y="Y" xp="XP" yp="YP"/>
.br
.B
</table>
.PP
where there can be 0 or more rows. The value of TYPE can be
.BR LOCATION ,
.BR PATH_START ,
.BR MOVE_TO ,
.BR SPLINE ,
.BR CONTROL ,
.BR SEG_END ,
.BR CLOSE ,
or
.BR PATH_END .
The value of
.I NAME
is an empty string unless the value of
.I TYPE
is
.B LOCATION
or
.BR PATH_START ,
in which case
.I NAME
should be a variable name acceptable for use in a programming language
(e.g., Java or ECMAScript). For the type
.BR LOCATION ,
.BR MOVE_TO ,
.BR SPLINE ,
.BR CONTROL ,
or
.BR SEG_END ,
the values
.I X
and
.I Y
must be the coordinates of a corresponding point in graph-coordinate-space
units, and XP and YP must be the corresponding coordinates in image-space
units, measured from the lower-left corner of the image so that X values
go from left to right and Y values go from bottom to top.
.PP
Finally, the file ends by closing the
.B epts
element:
.IP
.B
</epts>
.PP
as required for a valid XML file.
.SH TEMPLATE SYNTAX
Templates specify an output format for points and paths using the
syntax specified by the Java
class
.BR org.bzdev.util.TemplateProcessor .
Instances of this class are constructed using a tree consisting of
objects whose type is
.B org.bzdev.util.TemplateProcessor.KeyMap
or
.BR org.bzdev.util.TemplateProcessor.KeyMapList .
This tree determines the directives a give template processor supports
and how those directives are used. Each value corresponding to a key
is either a string (\fBjava.lang.String\fR), a
.BR KeyMap ,
an array of
.BR KeyMap , or a
.BR KeyMapList .
The keys name directives. When a key's value is a string, the
directive is a simple directive.  Otherwise it is an iterative
directive. When the value of an iterative directive is a single
.BR KeyMap ,
the iteration occurs once and this can be used a conditional (provided
when the directive is defined and missing when it is not defined).
.PP
A template contains a mixture of text and directives stored in a text
file. In a template, directives start with the sequence "$(" and end
with a closing ")".  A simple directive contains a variable name and
its value is a string that provides text that will be substituted for
the directive.  For example, the directive "$(varname)" will be
replaced by a string containing a variable name.  The directive "$$"
is replaced with a single dollar sign.  An iterative directive
consists of a name, a colon (":") and a second name. Its value is
either a key map (in which case it is treated like a list with a
single value, or a list or array providing key maps over which one
iterates). A following simple directive containing the second name
will then end the iterative block.
.PP
Directives can be globally defined or can be scoped to apply only
within an iterative block.  When blocks are nested and a directive is
defined at multiple levels, the most recent definition is used.
.SH TABLE TEMPLATE FORMAT
EPTS can generate text files, describing all paths and locations
stored in EPTS's table, based on a template.
.PP
For a table template, EPTS defines one global directive:
.BR items ,
which is an iterative directive.  This directive iterates over a list,
each element of which contains the following directives:
.TP
.BR varname .
This is a simple directive defining a variable name associated with a
location or path.
.TP
.BR index .
This directive provides an overall index. Its value is incremented for
each line in the table.
.TP
.BR vindex .
This directive provides a variable-name index. This value is
incremented whenever a variable name changes.
.TP
.BR location .
This is an iterative directive that defines a specific, isolated
point. While iterative, each definition contains only a single
point. Both
.B location
and
.B pathStatement
will not both be present at a specific iteration, although one of the
two will be present.
.TP
.BR pathStatement .
This is an iterative directive that defines the control points for a
path. While iterative, each pathSegment definition contains a single
key map as its value. Both
.B location
and
.B pathStatement
will not both be present at a specific iteration, although one of the
two will be present.
.PP
While
.B location
is an iterative directive, it acts as if there was a single
iteration. During this iteration, the following keys are defined:
.TP
.BR x .
This directive provides the X coordinate of the point in graph
coordinate space.
.TP
.BR y .
This directive provides the Y coordinate of the point in graph
coordinate space.
.TP
.BR xp .
This directive provides the X coordinate of the point in image space
measured from left to right (the standard Java convention).
.TP
.BR yp .
This directive provides the Y coordinate of the point in image space,
measured from top to bottom (the standard Java convention).
.TP
.BR ypr .
This directive provides the Y coordinate of the point in image space
measured from bottom to top (the reverse of the standard Java convention,
instead matching the convention used in mathematics).
.PP
Similarly, the value for
.B pathStatement
is a key map containing the following directives:
.TP
.BR hasWindingRule .
This is an iterative directive containing a single iteration. When
present, one may use the
.B windingRule
directive, whose values are
.B WIND_NON_ZERO
and
.BR WIND_EVEN_ODD .
.TP
.BR pindex .
The value is "1" for the initial
.B MOVE_TO
operation for a path and is incremented for each control point, spline
point, or end-of-segment point, along the path, and for a
final 'close' if there is one.
.TP
.BR type .
This is the type of a control point or operation
along the path (\fBMOVE_TO\fR,
.BR SPLINE ,
.BR CONTROL ,
.BR SEG_END ,
or
.BR CLOSE ).
.TP
.BR ltype .
This is similar to the
.B type
directive, but substitutes
.B CONTROL_POINT
for
.BR CONTROL , and
.B SPLINE_POINT
for
.BR SPLINE .
The directive
.B ltype is useful
for templates used to configure an instance of the class
.BR org.bzdev.anim2d.AnimationLayer2DFactory .
.TP
.BR atype .
This is is similar to
.B type
but with an alternative value defined by the user via a command-line
argument that provides the name of a file mapping types to their
replacement strings. The format of this file is described below. It
is useful for printing a representation of a table that will be used
in a report where terminology used for software is not appropriate.
.BR xy .
This is an iterative directive, with 0 or 1
iterations. It defines the following directives, the same ones
as defined by the location directive, when the type
is
.BR MOVE_TO ,
.BR SPLINE ,
.BR CONTROL ,
or
.BR SEG_END :
.BR x ,
.BR y ,
.BR xp ,
.BR yp ,
and
.BR ypj ,
with the same meaning as used in  the
.B location
directive.
.SH PATH-ITERATOR TEMPLATE FORMAT
These templates describe individual paths.
The global directives are
.TP
.BR area .
This directive contains the area of the shape. If constructed
from multiple paths, all of these paths must be closed paths: otherwise
the value will be "NaN". The units are either user-space units or GCS
units, depending on flags passed to
.BR epts .
When the
.BR epts
command contains the
.B \-\-gcs
option, GCS units are used; otherwise user-space units are used.
.TP
.BR circumference .
This directive contains the circumference of the shape. If constructed
from multiple paths, all of these paths must be closed paths: otherwise
the value will be "NaN". The units are either user-space units or GCS
units, depending on flags passed to
.BR epts .
When the
.BR epts
command contains the
.B \-\-gcs
option, GCS units are used; otherwise user-space units are used.

.TP
.BR pathLength .
This directive contains the path length for the boundary of a shape
regardless of whether it encloses an area. The units are either
user-space units or GCS units, depending on flags passed to
.BR epts .
When the
.BR epts
command contains the
.B \-\-gcs
option, GCS units are used; otherwise user-space units are used.
.TP
.BR varname .
This directive provides the name of the varible whose value is
the path that the following directives describe.
.TP
.BR windingRule .
This directive describes a winding rule, and is useful when a path
is closed, possibly containing muliple disjoint sections. The value
for this director is either
.B WIND_EVEN_ODD
or
.BR WIND_NON_ZERO .
.B WIND_EVEN_ODD
indicates that a point is inside a closed path if a ray drawn to infinity
crosses path segments an odd number of times.
.B WIND_NON_ZERO
indicates that a point is inside a closed path if a ray drawn to infinity
crosses segments drawn in the counterclockwise direction a different
number of times than segments drawn in the clockwise direction.
.TP
.B segments
This directive is an iterative directive.
.PP
The
.B segments
directive iterates over a list of keymaps, each of which contains
the following directives, all but one which are optional:
.TP
.B type
This is a mandatory directive. Its value can be
.BR SEG_CLOSE ,
.BR SEG_MOVETO ,
.BR SEG_LINETO ,
.BR SEG_QUADTO ,
or
.BR SEG_CUBICTO .
For each value, there is a corresponding iterative directive described
below.
.TP
.B method
This is a mandatory directive. Its value can be
.BR closePath ,
.BR moveTo ,
.BR lineTo ,
.BR quadTo ,
.BR curveTo .
These values correspond to the values provided for the
.B type
directive, but provide Java method names used by the
.B Path
class rather than constants provided by the class
.BR PathIterator .
.TP
.B hasClose
This is an iterative directive indicating that the type for the
current segment is
.B SEG_CLOSE .
.TP
.B hasMoveTo
This is an iterative directive indicating that the type for the
current segment is
.B SEG_MOVETO .
.TP
.B hasLineTo
This is an iterative directive indicating that the type for the
current segment is
.B SEG_LINETO .
.TP
.B hasQuadTo
This is an iterative directive indicating that the type for the
current segment is
.B SEG_QUADTO .
.TP
.B hasCubicTo
This is an iterative directive indicating that the type for the
current segment is
.B SEG_CUBICTO .
.PP
Each segment directive also contains the following optional
directives that provide the X and Y coordinates of a segment's
points:
.TP
.B x0
The X coordinate of the first control point. When the type
is
.BR SEG_MOVETO ,
this value represents the X coordinate of the start of a segment.
When the type is
.BR SEG_CLOSE ,
this value is not included in the key map and will therefore be
treated as zero-length text.  When the type is
.BR SEG_LINETO ,
this value represents the X coordinate at the end of the segment.
.TP
.B y0
The Y coordinate of the first control point. When the type
is
.BR SEG_MOVETO ,
this value represents the Y coordinate of the start of a segment.
When the type is
.BR SEG_CLOSE ,
this value is not included in the key map and will therefore be
treated as zero-length text. When the type is
.BR SEG_LINETO ,
this value represents the Y coordinate at the end of the segment.
.TP
.B x1
The X coordinate of the second control point. When the type is
.BR SEG_QUADTO ,
this value represents the X coordinate at the end of the segment.
It is empty when the type is
.B SEG_LINETO
or
.BR SEG_CLOSE .
.TP
.B y1
The Y coordinate of the second control point. When the type is
.BR SEG_QUADTO ,
this value represents the Y coordinate at the end of the segment.
It is empty when the type is
.B SEG_LINETO
or
.BR SEG_CLOSE .
.B x2
The X coordinate of the third control point. When the type is
.BR SEG_CUBICTO ,
this value represents the X coordinate at the end of the segment.
Otherwise, it is empty.
.TP
.B y2
The Y coordinate of the third control point. When the type is
.BR SEG_CUBICTO ,
this value represents the Y coordinate at the end of the segment.
Otherwise, it is empty.
.PP
There are several directives that indicate when
.BR x0 ,
.BR y0 ,
.BR x1 ,
.BR y1 ,
.BR x2 ,
or
.BR y2
exist and can be used as an alternative to the directives
.BR hasMoveTo ,
.BR hasLineTo ,
.BR hasQuadTo ,
.BR hasCubicTo .
These directives are the following:
.TP
.B has0
This is an iterative directive indicating that
.B x0
and
.B y0
exist.
.TP
.B has1
This is an iterative directive indicating that
.BR x0 ,
.BR y0 ,
.B x1
and
.B y1
exist.
.TP
.B has2
.BR x0 ,
.BR y0 ,
.BR x1 ,
.BR y1 ,
.B x2
and
.B y2
exist.
.SH MAP FILES
The
.B epts
command has an option
.B \-\-map
that specifies the strings for the "$(atype)" directive described above.
This argument takes a file name or URL as its argument. The file must
use UTF-8 as its character set. The format is trivial: a series of
lines.  Each line starts with one of the tokens provided by "$(type)":
.BR MOVE_TO ,
.BR SPLINE ,
.BR CONTROL ,
.BR SEG_END ,
or
.BR CLOSE .
This is separated from its replacement by whitespace.  Leading or
trailing whitespace is removed.
.SH SEE ALSO
.BR epts (1)
\"  LocalWords:  EPTS epts xml UTF br DOCTYPE xmlns fIWIDTH fB URI nm
\"  LocalWords:  fIHEIGHT imageURIExists fIVALUE targetList fICDATA
\"  LocalWords:  CDATA subdirectory gcsconfig unitIndex fIIND fIUDIST
\"  LocalWords:  refPointIndex userSpaceDistance gcsDistance xorigin
\"  LocalWords:  fIGCSDIST fIXORIGIN yorigin fIYORIGIN UDIST GCSDIST
\"  LocalWords:  varname fINAME fITYPE xp XP yp YP SEG fR KeyMap TP
\"  LocalWords:  KeyMapList vindex pathStatement pathSegment ypj xy
\"  LocalWords:  pindex fBMOVE ltype atype whitespace
