// This file was automatically generated by the epts program, and 
// should not be edited.
$(hasPackage:endPackage)package $(package);
$(endPackage)import java.awt.geom.Point2D;
$(public)$(optSpace)final class $(class) {
$(items:endItems)$(location:endLocation)    static final Point2D $(varname) = new Point2D.Double($(x), y: $(y));
$(endLocation)$(endItems)}
