// This file was automatically generated by the epts program, and 
// should not be edited.
$(hasPackage:endPackage)package $(package);
$(endPackage)import org.bzdev.anim2d.AbstrAnimLayer2DFactory;
import org.bzdev.anim2d.AnimationLayer2D;
import org.bzdev.anim2d.AnimationLayer2D.Type;
import org.bzdev.geom.SplinePathBuilder;
import org.bzdev.geom.SplinePathBuilder.WindingRule;
import org.bzdev.obnaming.NamedObjectFactory;
import org.bzdev.obnaming.NamedObjectFactory.IndexedSetter;
$(public)$(optSpace)final class $(class) implements IndexedSetter {
$(items:endItems)$(pathStatement:endPathStatement)    public static IndexedSetter $(varname) = new IndexedSetter() {
        public int setIndexed(AbstrAnimLayer2DFactory f, int start) {
            f.set("object.type", start, Type.PATH_START);
$(hasWindingRule:endWR)            f.set("object.windingRule", start, WindingRule.$(windingRule));
$(endWR)            start++;
$(pathItem:endPathItem)            f.set("object.type", start, Type.$(ltype));
$(xy:endXY)            f.set("object.x", start, $(x));
            f.set("object.y", start, $(y));
$(endXY)            start++;
$(endPathItem)            f.set("object.type", start, Type.PATH_END);
	    f.set("object.draw", start, "$(draw)");
	    f.set("object.fill", start, "$(fill)");$(hasGcsMode:endGcsMode)
	    f.set("object.stroke.gcsMode", start, $(gcsMode));$(endGcsMode)$(hasDrawColor:endDrawColor)
	    f.set("object.drawColor.css", start, "$(drawColor)");$(endDrawColor)$(hasFillColor:endFillColor)
	    f.set("object.fillColor.css", start, "$(fillColor)");$(endFillColor)$(hasStrokeCap:endStrokeCap)
	    f.set("object.stroke.cap", start, "$(strokeCap)");$(endStrokeCap)$(hasDashIncrement:endDashIncrement)
	    f.set("object.stroke.dashIncrement", start, $(dashIncrement));$(endDashIncrement)$(hasDashPhase:endDashPhase)
	    f.set("object.stroke.dashPhase", start, $(dashPhase));$(endDashPhase)$(hasDashPattern:endDashPattern)
	    f.set("object.stroke.dashPattern", start, "$(dashPattern)");$(endDashPattern)$(hasStrokeJoin:endStrokeJoin)
	    f.set("object.stroke.join", start, "$(strokeJoin)");$(endStrokeJoin)$(hasMiterLimit:endMiterLimit)
	    f.set("object.stroke.miterLimit", start, $(miterLimit));$(endMiterLimit)$(hasStrokeWidth:endStrokeWidth)
	    f.set("object.stroke.width", start, $(strokeWidth));$(endStrokeWidth)
	    start++;
            return start;
        }
    }
$(endPathStatement)$(endItems)    public setIndexed(AbstrAnimLayer2DFactory f, int start) {
$(items:endItems)$(pathStatement:endPathStatement)       start = $(class).$(varname).setIndexed(f, start);
$(endPathStatement)$(endItems)        return start;
    }
}
