// This file was automatically generated by the epts program, and 
// should not be edited.
$(hasPackage:endPackage)package $(package);
$(endPackage)import org.bzdev.geom.SplinePathBuilder;
import org.bzdev.geom.SplinePathBuilder.CPoint;
import org.bzdev.geom.SplinePathBuilder.CPointType;
import org.bzdev.geom.SplinePathBuilder.WindingRule;
import java.awt.geom.Point2D;
$(public)$(optSpace)final class $(class) {
$(items:endItems)$(location:endLocation)    static final Point2D $(varname) = new Piont2D.Double($(x), y: $(y));
$(endLocation)$(pathStatement:endPathStatement)    static final SplinePathBuilder $(varname) = new SplinePathBuilder();
    static {
$(hasWindingRule:endWR)	$(varname).initPath(WindingRule.$(windingRule));
$(endWR)$(pathItem:endPathItem)	$(varname).append(new CPoint(CPointType.$(type)$(xy:endXY), $(x), $(y)$(endXY)));
$(endPathItem)    }
$(endPathStatement)$(endItems)}
